export const initialRegisterForm = {
  first_name: '',
  last_name: '',
  phone: '',
  email: '',
  password: '',
  role: 'client',
  vehicle_number: '',
  vehicle_category: 'A',
}

export const initialLoginForm = {
  email: '',
  password: '',
}

export const initialBookingForm = {
  pickup_address: '',
  destination_address: '',
  vehicle_category: 'A',
  weight_kg: '',
}

export const initialPasswordForm = {
  current_password: '',
  password: '',
  password_confirmation: '',
}

export const initialAdminProfileForm = {
  name: '',
  email: '',
}

export const routes = {
  home: '/',
  client: '/client',
  driver: '/driver',
  driverCommands: '/driver/commands',
  driverMap: '/driver/map',
  driverDashboard: '/driver/dashboard',
  admin: '/admin',
  register: '/register',
  login: '/login',
  book: '/book',
  track: '/track',
  dashboard: '/dashboard',
}

export function getViewFromPath() {
  const path = window.location.pathname

  if (path === routes.client) return 'client'
  if (path === routes.driver) return 'driver'
  if (path === routes.driverCommands) return 'driverCommands'
  if (path === routes.driverMap) return 'driverMap'
  if (path === routes.driverDashboard) return 'driverDashboard'
  if (path === routes.admin) return 'admin'
  if (path === routes.register) return 'register'
  if (path === routes.login) return 'login'
  if (path === routes.book) return 'book'
  if (path === routes.track) return 'track'
  if (path === routes.dashboard) return 'dashboard'

  return 'home'
}

export function readStoredClient() {
  try {
    const account = JSON.parse(window.localStorage.getItem('na9l_account')) || null
    if (account) return account

    const client = JSON.parse(window.localStorage.getItem('na9l_client')) || null
    return client ? { ...client, role: 'client' } : null
  } catch {
    return null
  }
}

export const copy = {
  fr: {
    nav: {
      home: 'Accueil',
      client: 'Client',
      driver: 'Driver',
      register: 'Inscription',
      login: 'Connexion',
      book: 'Book',
      track: 'Track',
      dashboard: 'Dashboard',
      commands: 'Requests',
      logout: 'Deconnexion',
      admin: 'Admin',
    },
    hero: {
      eyebrow: 'Logistique intelligente au Maroc',
      title: 'Livraison rapide et fiable',
      text:
        'Na9l Pro est une plateforme de transport qui connecte les clients aux chauffeurs verifies pour livrer marchandises, colis et biens professionnels en toute confiance.',
      primary: 'Creer un compte',
      secondary: 'Voir les etapes',
    },
    stats: [
      { value: '24/7', label: 'suivi des livraisons' },
      { value: '2 roles', label: 'client et driver' },
    ],
    badges: ['Chauffeurs verifies', 'Commandes suivies', 'Livraison de biens'],
    process: {
      label: 'Experience de livraison',
      title: 'Un parcours clair pour les clients et les drivers',
    },
    workflow: [
      {
        icon: 'box',
        label: 'Client',
        title: 'Creation du compte',
        text: 'Creez votre compte et completez les informations de livraison.',
      },
      {
        icon: 'route',
        label: 'Client',
        title: 'Reservation du trajet',
        text: 'Ajoutez la marchandise, le depart et l adresse de destination.',
      },
      {
        icon: 'truck',
        label: 'Driver',
        title: 'Commandes disponibles',
        text: 'Les missions proches s affichent avec tous les details utiles.',
      },
      {
        icon: 'check',
        label: 'Driver',
        title: 'Acceptation rapide',
        text: 'Le driver accepte, recupere la marchandise et confirme la livraison.',
      },
    ],
    client: {
      label: 'Parcours client',
      title: 'Comment reserver un chauffeur',
      steps: [
        'Creez un compte client et completez vos informations.',
        'Ajoutez la marchandise, le point de depart et l adresse de livraison.',
        'Suivez le chauffeur jusqu a la livraison finale.',
      ],
    },
    driver: {
      label: 'Parcours driver',
      title: 'Comment accepter des commandes',
      steps: [
        'Creez un compte driver avec vos informations et documents.',
        'Recevez les commandes disponibles avec les details du trajet.',
        'Acceptez la mission, recuperez la marchandise et livrez-la.',
      ],
    },
    registerForm: {
      label: 'Inscription',
      title: 'Creez votre compte Na9l Pro',
      text: 'Choisissez votre role et ajoutez les informations necessaires pour demarrer.',
      firstName: 'Prenom',
      lastName: 'Nom',
      phone: 'Numero de telephone',
      email: 'Email',
      password: 'Mot de passe',
      role: 'Type de compte',
      client: 'Client',
      driver: 'Driver',
      vehicleNumber: 'Numero du vehicule',
      vehicleCategory: 'Categorie du vehicule',
      submit: 'Enregistrer',
      saving: 'Enregistrement...',
      success: 'Inscription enregistree avec succes.',
      error: 'Impossible d enregistrer l inscription.',
      categories: {
        A: 'Categorie A - Caddy, Doker, Partner, Fiat Doublo',
        B: 'Categorie B - Mini van',
        C: 'Categorie C - Camion',
      },
    },
    loginPage: {
      label: 'Connexion',
      title: 'Connectez-vous a Na9l Pro',
      text: 'Accedez a votre espace pour suivre vos livraisons, gerer vos missions et rester connecte a votre activite.',
      submit: 'Se connecter',
      saving: 'Connexion...',
      success: 'Connexion reussie.',
      error: 'Email ou mot de passe incorrect.',
    },
    profile: {
      editProfile: 'Edit profil',
      editPassword: 'Edit mot passe',
      manageAccount: 'Gere account',
      profileTitle: 'Modifier le profil',
      passwordTitle: 'Modifier le mot de passe',
      currentPassword: 'Mot de passe actuel',
      newPassword: 'Nouveau mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      save: 'Enregistrer',
      saving: 'Enregistrement...',
      close: 'Fermer',
      profileSuccess: 'Profil mis a jour.',
      passwordSuccess: 'Mot de passe mis a jour.',
      profileError: 'Impossible de modifier le profil.',
      passwordError: 'Impossible de modifier le mot de passe.',
    },
    clientSpace: {
      bookingLabel: 'Nouvelle commande',
      bookingTitle: 'Reserve ton transport',
      bookingText: 'Ajoute le depart, la destination, la categorie du vehicule et le poids de la marchandise.',
      pickup: 'Adresse de depart',
      destination: 'Adresse de destination',
      category: 'Categorie du vehicule',
      weight: 'Poids en KG',
      submit: 'Enregistrer la commande',
      saving: 'Enregistrement...',
      success: 'Commande enregistree avec succes.',
      error: 'Impossible d enregistrer la commande.',
      loading: 'Chargement...',
      trackLabel: 'Suivi',
      trackTitle: 'Suivre le driver',
      trackText: 'La carte affiche le trajet de ta derniere commande active.',
      noBooking: 'Aucune commande active pour le moment.',
      mapFallback: 'Carte chargee avec une position approximative. Ajoute une adresse plus precise pour un trajet exact.',
      dashboardLabel: 'Dashboard',
      dashboardTitle: 'Tes commandes et drivers',
      dashboardText: 'Consulte les commandes deja creees et les drivers qui ont travaille avec toi.',
      noDrivers: 'Aucun driver encore assigne.',
      noOrders: 'Aucune commande enregistree.',
      loginRequired: 'Connecte-toi comme client pour acceder a cet espace.',
      callDriver: 'Call driver',
    },
    driverSpace: {
      commandsLabel: 'Commandes disponibles',
      commandsTitle: 'Les demandes client proches de ton vehicule',
      commandsText: 'Accepte une commande, consulte le client, puis suis le trajet sur la carte.',
      dashboardLabel: 'Dashboard driver',
      dashboardTitle: 'Ton activite et tes revenus',
      dashboardText: 'Consulte les commandes acceptees, les clients servis et les informations de ton vehicule.',
      mapLabel: 'Mission active',
      mapTitle: 'Trajet client',
      mapText: 'La carte affiche le depart et la destination de la commande acceptee.',
      accept: 'Accepter',
      accepting: 'Acceptation...',
      success: 'Commande acceptee.',
      error: 'Impossible de charger les commandes.',
      noCommands: 'Aucune commande disponible pour ta categorie.',
      noMission: 'Aucune mission active pour le moment.',
      loginRequired: 'Connecte-toi comme driver pour acceder a cet espace.',
      jobs: 'missions',
      earnings: 'revenus',
      clients: 'clients',
      driverInfo: 'Informations driver',
      vehicleInfo: 'Vehicule',
      callClient: 'Call client',
    },
    adminSpace: {
      label: 'Espace prive',
      title: 'Dashboard admin',
      text: 'Controle les clients, drivers, requests et comptes de toute la plateforme.',
      clients: 'Clients',
      drivers: 'Drivers',
      requests: 'Requests',
      pending: 'En attente',
      accepted: 'Acceptees',
      delivered: 'Livrees',
      edit: 'Modifier',
      delete: 'Supprimer',
      save: 'Sauvegarder',
      cancel: 'Annuler',
      passwordHint: 'Le mot de passe actuel est visible. Ajoute un nouveau mot de passe seulement pour le remplacer.',
      passwordStatus: 'Mot de passe',
      status: 'Status',
      assignDriver: 'Driver',
      noDriver: 'Aucun driver',
      confirmDelete: 'Supprimer cet element ?',
      success: 'Action admin executee.',
      error: 'Action admin impossible.',
    },
  },
  ar: {
    nav: {
      home: 'الرئيسية',
      client: 'العميل',
      driver: 'السائق',
      register: 'تسجيل',
      login: 'دخول',
      book: 'حجز',
      track: 'تتبع',
      dashboard: 'لوحة التحكم',
      commands: 'الطلبات',
      logout: 'خروج',
      admin: 'Admin',
    },
    hero: {
      eyebrow: 'لوجستيك ذكي داخل المغرب',
      title: 'توصيل سريع وموثوق',
      text:
        'نقل برو منصة نقل كتربط العملاء بسائقين موثوقين باش توصل السلع، الطرود، والحاجيات المهنية بطريقة منظمة وآمنة.',
      primary: 'إنشاء حساب',
      secondary: 'مشاهدة الخطوات',
    },
    stats: [
      { value: '24/7', label: 'تتبع التوصيل' },
      { value: '2 أدوار', label: 'عميل وسائق' },
    ],
    badges: ['سائقون موثوقون', 'طلبات قابلة للتتبع', 'نقل السلع'],
    process: {
      label: 'تجربة التوصيل',
      title: 'مسار واضح للعميل والسائق',
    },
    workflow: [
      {
        icon: 'box',
        label: 'العميل',
        title: 'إنشاء الحساب',
        text: 'أنشئ حسابك وأكمل معلومات التوصيل.',
      },
      {
        icon: 'route',
        label: 'العميل',
        title: 'حجز الرحلة',
        text: 'أضف السلعة، نقطة الانطلاق، وعنوان التسليم.',
      },
      {
        icon: 'truck',
        label: 'السائق',
        title: 'الطلبات المتاحة',
        text: 'تظهر الطلبات القريبة مع تفاصيل المسار والسلعة.',
      },
      {
        icon: 'check',
        label: 'السائق',
        title: 'قبول سريع',
        text: 'يقبل السائق الطلب، يستلم السلعة، ويؤكد التسليم.',
      },
    ],
    client: {
      label: 'مسار العميل',
      title: 'كيف تحجز سائقا',
      steps: [
        'أنشئ حساب عميل وأكمل معلوماتك.',
        'أضف السلعة، نقطة الانطلاق، وعنوان التسليم.',
        'تتبع السائق إلى أن تصل السلعة.',
      ],
    },
    driver: {
      label: 'مسار السائق',
      title: 'كيف تقبل الطلبات',
      steps: [
        'أنشئ حساب سائق مع المعلومات والوثائق.',
        'توصل بالطلبات المتاحة مع تفاصيل الرحلة.',
        'اقبل المهمة، استلم السلعة، وسلمها للعميل.',
      ],
    },
    registerForm: {
      label: 'التسجيل',
      title: 'أنشئ حسابك في نقل برو',
      text: 'اختر نوع الحساب وأدخل المعلومات اللازمة للبداية.',
      firstName: 'الاسم',
      lastName: 'الكنية',
      phone: 'رقم الهاتف',
      email: 'البريد الإلكتروني',
      password: 'كلمة السر',
      role: 'نوع الحساب',
      client: 'عميل',
      driver: 'سائق',
      vehicleNumber: 'رقم السيارة',
      vehicleCategory: 'صنف السيارة',
      submit: 'تسجيل',
      saving: 'جاري التسجيل...',
      success: 'تم حفظ التسجيل بنجاح.',
      error: 'تعذر حفظ التسجيل.',
      categories: {
        A: 'الصنف A - Caddy, Doker, Partner, Fiat Doublo',
        B: 'الصنف B - Mini van',
        C: 'الصنف C - Camion',
      },
    },
    loginPage: {
      label: 'دخول',
      title: 'ادخل إلى حساب نقل برو',
      text: 'تابع التوصيلات، نظم المهام، وخليك قريب من نشاطك اليومي.',
      submit: 'دخول',
      saving: 'جاري الدخول...',
      success: 'تم الدخول بنجاح.',
      error: 'البريد أو كلمة السر غير صحيحة.',
    },
    profile: {
      editProfile: 'تعديل البروفيل',
      editPassword: 'تعديل كلمة السر',
      manageAccount: 'تسيير الحساب',
      profileTitle: 'تعديل البروفيل',
      passwordTitle: 'تعديل كلمة السر',
      currentPassword: 'كلمة السر الحالية',
      newPassword: 'كلمة السر الجديدة',
      confirmPassword: 'تأكيد كلمة السر',
      save: 'حفظ',
      saving: 'جاري الحفظ...',
      close: 'إغلاق',
      profileSuccess: 'تم تحديث البروفيل.',
      passwordSuccess: 'تم تحديث كلمة السر.',
      profileError: 'تعذر تحديث البروفيل.',
      passwordError: 'تعذر تحديث كلمة السر.',
    },
    clientSpace: {
      bookingLabel: 'طلب جديد',
      bookingTitle: 'احجز النقل ديالك',
      bookingText: 'دخل نقطة الانطلاق، الوجهة، صنف السيارة، ووزن السلعة.',
      pickup: 'عنوان الانطلاق',
      destination: 'عنوان الوصول',
      category: 'صنف السيارة',
      weight: 'الوزن بالكيلو',
      submit: 'حفظ الطلب',
      saving: 'جاري الحفظ...',
      success: 'تم حفظ الطلب بنجاح.',
      error: 'تعذر حفظ الطلب.',
      loading: 'جاري التحميل...',
      trackLabel: 'التتبع',
      trackTitle: 'تتبع السائق',
      trackText: 'الخريطة كتبيّن مسار آخر طلب نشيط.',
      noBooking: 'لا يوجد طلب نشيط حاليا.',
      mapFallback: 'الخريطة خدامة بموقع تقريبي. زيد عنوان واضح باش يبان المسار بدقة.',
      dashboardLabel: 'لوحة التحكم',
      dashboardTitle: 'طلباتك والسائقين',
      dashboardText: 'شوف الطلبات اللي درتي والسائقين اللي خدمو معاك.',
      noDrivers: 'مازال ما تعين حتى سائق.',
      noOrders: 'مازال ماكاين حتى طلب.',
      loginRequired: 'دخل كعميل باش تستعمل هاد الفضاء.',
      callDriver: 'اتصل بالسائق',
    },
    driverSpace: {
      commandsLabel: 'الطلبات المتاحة',
      commandsTitle: 'طلبات العملاء المناسبة للسيارة ديالك',
      commandsText: 'اقبل الطلب، شوف معلومات العميل، ومن بعد تتبع الرحلة فالخريطة.',
      dashboardLabel: 'لوحة السائق',
      dashboardTitle: 'الخدمة والمداخيل ديالك',
      dashboardText: 'شوف الطلبات اللي قبلتي، العملاء اللي خدمتي معاهم، ومعلومات السيارة.',
      mapLabel: 'مهمة نشيطة',
      mapTitle: 'مسار العميل',
      mapText: 'الخريطة كتبيّن الانطلاق والوجهة ديال الطلب اللي قبلتي.',
      accept: 'قبول',
      accepting: 'كيقبل...',
      success: 'تم قبول الطلب.',
      error: 'تعذر تحميل الطلبات.',
      noCommands: 'ماكاين حتى طلب مناسب لصنف السيارة ديالك.',
      noMission: 'ماكاينة حتى مهمة نشيطة حاليا.',
      loginRequired: 'دخل كسائق باش تستعمل هاد الفضاء.',
      jobs: 'مهمات',
      earnings: 'المداخيل',
      clients: 'عملاء',
      driverInfo: 'معلومات السائق',
      vehicleInfo: 'السيارة',
      callClient: 'اتصل بالعميل',
    },
    adminSpace: {
      label: 'فضاء خاص',
      title: 'لوحة الأدمن',
      text: 'تحكم فالعملاء، السائقين، الطلبات، والحسابات ديال المنصة كاملة.',
      clients: 'العملاء',
      drivers: 'السائقين',
      requests: 'الطلبات',
      pending: 'في الانتظار',
      accepted: 'مقبولة',
      delivered: 'واصلة',
      edit: 'تعديل',
      delete: 'حذف',
      save: 'حفظ',
      cancel: 'إلغاء',
      passwordHint: 'كلمة السر الحالية باينة. دخل كلمة سر جديدة فقط إلا بغيتي تبدلها.',
      passwordStatus: 'كلمة السر',
      status: 'الحالة',
      assignDriver: 'السائق',
      noDriver: 'بدون سائق',
      confirmDelete: 'واش تحذف هذا العنصر؟',
      success: 'تم تنفيذ العملية.',
      error: 'تعذر تنفيذ العملية.',
    },
  },
}
